name: LeeL-Blog
url: http://LeeL-Systems.github.io
baseurl: /LeeL-Blog
description: Blog for Free using Evernote and Github
avatar: https://avatars3.githubusercontent.com/u/3682638?v=3&s=460
disqus: leelsystems
google_analytics: UA-63442817-2
categoryConfigByCategory:
  Blog:
    display-style: post
    menu-position: -1
    header-position: 0
    foot-position: -1
siteConfigBySite:
  Github:
    link: https://github.com/LeeL-Systems
    display-style: socialMedia
    position: 0
markdown: kramdown
highlighter: pygments
permalink: /:title/
version: v1.0.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
  - jemoji
  - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md